export * from './avatar.design';
export * from './header.design';
export * from './heading.design';
export * from './image.component';
export * from './no_result.design';
export * from './pagination.design';
export * from './question.design';
export * from './step.design';
export * from './upload.design';
